import type { BlogPost, Category } from '../types';

// MDX module shape: each .mdx file exports frontmatter + a default React component
interface MdxModule {
  default: React.ComponentType;
  frontmatter: {
    title: string;
    excerpt: string;
    date: string;
    readTime?: string;
    categories: Category[];
    featured?: boolean;
    image?: string;
    imageAspectRatio?: string;
    authorId: string;
    tags?: string[];
  };
}

// Build-time glob import: all .mdx files as compiled modules
const postModules = import.meta.glob<MdxModule>('../content/posts/*.mdx', {
  eager: true,
});

function parsePost(filePath: string, mod: MdxModule): BlogPost {
  const { frontmatter, default: Content } = mod;

  // Derive slug from filename: '../content/posts/digital-declutter.mdx' → 'digital-declutter'
  const slug = filePath.split('/').pop()!.replace(/\.mdx$/, '');

  return {
    id: slug,
    slug,
    title: frontmatter.title,
    excerpt: frontmatter.excerpt,
    date: frontmatter.date,
    readTime: frontmatter.readTime ?? '1 min read',
    categories: Array.isArray(frontmatter.categories)
      ? frontmatter.categories
      : frontmatter.categories
        ? [frontmatter.categories as unknown as Category]
        : [],
    featured: frontmatter.featured ?? false,
    image: frontmatter.image || undefined,
    imageAspectRatio: frontmatter.imageAspectRatio,
    authorId: frontmatter.authorId,
    tags: frontmatter.tags ?? [],
    content: Content,
  };
}

// Parse all posts once, sorted newest-first
const allPosts: BlogPost[] = Object.entries(postModules)
  .map(([path, mod]) => parsePost(path, mod))
  .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

/** Get all posts, sorted newest-first */
export function getAllPosts(): BlogPost[] {
  return allPosts;
}

/** Get a single post by slug, or undefined */
export function getPostBySlug(slug: string): BlogPost | undefined {
  return allPosts.find((p) => p.slug === slug);
}

// Full-text search index (generated by npm run build-search-index)
import searchIndex from './search-index.json';
const searchData = searchIndex as Record<string, string>;

/** Search and filter posts by query string and/or tags */
export function searchPosts(
  source: BlogPost[],
  query: string,
  activeTags: string[]
): BlogPost[] {
  let results = source;

  if (query) {
    const q = query.toLowerCase();
    // Word-boundary regex for full-text body search to avoid substring false positives
    const wordPattern = new RegExp(`\\b${q.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`);
    results = results.filter(
      (p) =>
        p.title.toLowerCase().includes(q) ||
        p.excerpt.toLowerCase().includes(q) ||
        p.tags?.some((t) => t.toLowerCase().includes(q)) ||
        wordPattern.test(searchData[p.slug] ?? '')
    );
  }

  if (activeTags.length > 0) {
    results = results.filter((p) =>
      activeTags.every((tag) => p.tags?.includes(tag))
    );
  }

  return results;
}

// Backward-compatible named export
export const posts = allPosts;
